import { v4 as uuid } from 'uuid';
import { HighlightDto } from '../models/highlight.dto';

export const templates: HighlightDto[] = [
  {
    url: 'highlight1.mp4',
    homeTeam: 'Arsenal',
    awayTeam: 'Manchester City',
    competition: 'Premier League',
    matchDate: new Date(2025, 8, 12),
    id: uuid(),
    uploadDate: new Date(2025, 8, 13),
    likes: 750,
    thumbnailUrl: 'thumbnail1.jpg',
  },
  {
    url: 'highlight2.mp4',
    homeTeam: 'Aston Villa',
    awayTeam: 'Manchester City',
    competition: 'Premier League',
    matchDate: new Date(2025, 10, 26),
    id: uuid(),
    uploadDate: new Date(2025, 10, 27),
    likes: 1000,
    thumbnailUrl: 'thumbnail2.jpg',
  },
  {
    url: 'highlight3.mp4',
    homeTeam: 'Villarreal',
    awayTeam: 'Manchester City',
    competition: 'Champions League',
    matchDate: new Date(2025, 10, 21),
    id: uuid(),
    uploadDate: new Date(2025, 10, 22),
    likes: 1000,
    thumbnailUrl: 'thumbnail3.jpg',
  },
  {
    url: 'highlight4.mp4',
    homeTeam: 'Real Madrid',
    awayTeam: 'FC Barcelona',
    competition: 'La Liga',
    matchDate: new Date(2025, 10, 26),
    id: uuid(),
    uploadDate: new Date(2025, 10, 26),
    likes: 678,
    thumbnailUrl: 'thumbnail4.jpg',
  },
  {
    url: 'highlight5.mp4',
    homeTeam: 'FC Barcelona',
    awayTeam: 'PSG',
    competition: 'Champions League',
    matchDate: new Date(2017, 3, 8),
    id: uuid(),
    uploadDate: new Date(2017, 3, 9),
    likes: 909,
    thumbnailUrl: 'thumbnail5.jpg',
  },
  {
    url: 'highlight6.mp4',
    homeTeam: 'ATLETICO MADRID',
    awayTeam: 'FC Barcelona',
    competition: 'La Liga',
    matchDate: new Date(2025, 3, 17),
    id: uuid(),
    uploadDate: new Date(2025, 3, 17),
    likes: 877,
    thumbnailUrl: 'thumbnail6.jpg',
  },
  {
    url: 'highlight7.mp4',
    homeTeam: 'Real Madrid',
    awayTeam: 'Espanyol',
    competition: 'La Liga',
    matchDate: new Date(2025, 9, 21),
    id: uuid(),
    uploadDate: new Date(2025, 9, 21),
    likes: 2678,
    thumbnailUrl: 'thumbnail7.jpg',
  },
  {
    url: 'highlight8.mp4',
    homeTeam: 'Ajax Amsterdam',
    awayTeam: 'Tottenham Hotspur',
    competition: 'Champions League',
    matchDate: new Date(2019, 5, 12),
    id: uuid(),
    uploadDate: new Date(2019, 5, 13),
    likes: 678,
    thumbnailUrl: 'thumbnail8.jpg',
  },
  {
    url: 'highlight9.mp4',
    homeTeam: 'Borussia Dortmund',
    awayTeam: 'Malaga',
    competition: 'Champions League',
    matchDate: new Date(2013, 4, 9),
    id: uuid(),
    uploadDate: new Date(2013, 4, 10),
    likes: 678,
    thumbnailUrl: 'thumbnail9.jpg',
  },
  {
    url: 'highlight10.mp4',
    homeTeam: 'JUVENTUS',
    awayTeam: 'ATLETICO MADRID',
    competition: 'Champions League',
    matchDate: new Date(2019, 3, 15),
    id: uuid(),
    uploadDate: new Date(2019, 3, 16),
    likes: 678,
    thumbnailUrl: 'thumbnail10.jpg',
  }
];